import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Logo = () => (
  <div className="w-8 h-8 flex items-center justify-center bg-linear-to-br from-blue-700 to-violet-700 rounded-lg">
    <span className="font-bold text-sm">ML</span>
  </div>
);

const MenuButton = () => {
  return (
    <label htmlFor="menu-toggle" className="cursor-pointer w-8 h-8 border border-slate-700 rounded-lg flex flex-col justify-center items-center p-2 md:hidden">
      <span className="border rounded-xs w-full my-0.5"></span>
      <span className="border rounded-xs w-full my-0.5"></span>
      <span className="border rounded-xs w-full my-0.5"></span>
    </label>
  )
}

const Header = () => {
  return (
    <div className="w-full md:max-w-6xl md:mx-auto h-16 max-h-16 border-b border-slate-700 bg-slate-900 z-50 sticky top-0 flex items-center">
      <header className="w-full mx-auto p-4 flex flex-col md:flex-row justify-between items-center space-x-4">
        <input type="checkbox" id="menu-toggle" className="hidden peer" />
        <div className="w-11/12 flex justify-between md:justify-start items-center space-x-2 mr-0">
          <Logo />
          <span className="text-xl font-black text-center">Martin Lefebvre</span>
          <MenuButton />
        </div>
        <div className="w-11/12 hidden md:flex peer-checked:flex peer-checked:justify-between transition-all duration-800 mr-0">
          <nav className="w-full md:inlide md:w-auto border md:border-0 md:bg-transparent p-2 rounded-xl border-slate-700 bg-slate-800 my-2 z-50">
            <ul className="flex flex-col md:flex-row space-x-8 text-slate-400">
              <li><a href="#home" className="hover:underline my-0.5">Home</a></li>
              <li><a href="#about" className="hover:underline my-0.5">About</a></li>
              <li><a href="#resume" className="hover:underline my-0.5">Resume</a></li>
              <li><a href="#portfolio" className="hover:underline my-0.5">Portfolio</a></li>
              <li><a href="#contact" className="hover:underline my-0.5">Contact</a></li>
            </ul>
          </nav>
        </div>
        <div>
          hello
        </div>
      </header>
    </div>
  )
};

const Footer = () => (
  <footer className="max-w-6xl mx-auto p-4">
    <p className="text-sm text-center">&copy; 2024 My Next.js App</p>
  </footer>
);
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
