import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faEnvelope, faRss } from "@fortawesome/free-solid-svg-icons";
import { faGithub, faLinkedin } from "@fortawesome/free-brands-svg-icons";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Logo = () => (
  <div className="w-8 h-8 flex items-center justify-center bg-linear-to-br from-blue-700 to-violet-700 rounded-lg">
    <span className="font-bold text-sm">ML</span>
  </div>
);

const MenuButton = () => {
  return (
    <label htmlFor="menu-toggle" className="cursor-pointer w-8 h-8 border border-slate-700 rounded-lg flex flex-col justify-center items-center p-2 lg:hidden">
      <span className="border rounded-xs w-full my-0.5"></span>
      <span className="border rounded-xs w-full my-0.5"></span>
      <span className="border rounded-xs w-full my-0.5"></span>
    </label>
  )
}

const Header = () => {
  return (
    <div className="w-full lg:max-w-6xl lg:mx-auto h-16 max-h-16 border-b border-slate-700 bg-slate-900 z-50 sticky top-0 lg:flex items-center">
      <header className="w-full mx-auto p-4 flex flex-col lg:flex-row justify-between items-center space-x-4">
        <input type="checkbox" id="menu-toggle" className="hidden peer" />
        <div className="w-11/12 flex justify-between lg:justify-start items-center space-x-2 mr-0">
          <Logo />
          <span className="text-xl font-black text-center">Martin Lefebvre <span className="text-md font-thin hidden md:inline lg:hidden">Full Stack Developer</span></span>
          <MenuButton />
        </div>
        <div className="w-11/12 hidden lg:flex peer-checked:flex peer-checked:justify-between transition-all duration-800 mr-0">
          <nav className="w-full lg:inline lg:w-auto border lg:border-0 lg:bg-transparent p-2 rounded-xl border-slate-700 bg-slate-800 my-2 z-50">
            <ul className="flex flex-col lg:flex-row space-x-8 text-slate-400">
              <li><a href="/" className="hover:underline my-0.5">Home</a></li>
              <li><a href="/about" className="hover:underline my-0.5">About</a></li>
              <li><a href="/resume" className="hover:underline my-0.5">Resume</a></li>
              <li><a href="/portfolio" className="hover:underline my-0.5">Portfolio</a></li>
              <li><a href="/contact" className="hover:underline my-0.5">Contact</a></li>
            </ul>
          </nav>
        </div>
        <div className="w-11/12 hidden lg:flex justify-end items-center space-x-2 mr-0">
          <FontAwesomeIcon icon={faRss} className="w-6 h-6 text-slate-400 hover:text-slate-200 cursor-pointer mr-4" />
          <FontAwesomeIcon icon={faEnvelope} className="w-6 h-6 text-slate-400 hover:text-slate-200 cursor-pointer mr-4" />
          <FontAwesomeIcon icon={faGithub} className="w-6 h-6 text-slate-400 hover:text-slate-200 cursor-pointer mr-4" />
          <FontAwesomeIcon icon={faLinkedin} className="w-6 h-6 text-slate-400 hover:text-slate-200 cursor-pointer" />
        </div>
      </header>
    </div>
  )
};

const Footer = () => (
  <footer className="max-w-6xl mx-auto p-4">
    <p className="text-sm text-center">&copy; 2024 My Next.js App</p>
  </footer>
);
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased scroll-smooth`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
